### PR TITLE
Remove line between "Edit Containers"  and "+"

### PR DESCRIPTION
**Pull request by Shourai**
image
to
image

### CODE REVIEW

**Comment by overdodactyl** [comment]
Thanks! The fix for Containers extension has been included (I merged it locally, but that still [retains authorship](https://github.com/overdodactyl/ShadowFox/graphs/contributors) of the tweak).  

I think the padding in the context menus might be good to keep to maintain similar spacing above/below all items and keep in similar to the original ones:

screen shot 2018-03-08 at 8 37 31 am

Left is no changes, right is with padding removed

**Comment by Shourai** [comment]
Thanks for the merge!
Regarding the context menu, for the #context-navigation the padding creates a tiny grey-60 padding
above it which doesn't blend in very well.
I thought of two options to mediate this, either remove the padding or changing everything in the context menu to grey-60.
I chose for the latter option and left the padding now as is.

**Comment by overdodactyl** [comment]
Removing the darker color on the top navigation buttons but be a good way to go.  I'll play with that look a bit.

**Comment by overdodactyl** [comment]
The darker color on the navigation items has now been removed

**Pull request closed without merging**
